### ISSUE TITLE
For univariate distributions, calling pdf on an array of values is deprecated

### ISSUE THREAD

**Issue by fpmenninger** [StatisticalRethinkingJulia/StatisticalRethinkingTuring.jl#12]
For univariate distributions, calling pdf on an array of values is deprecated. Nevertheless it should not throw an error but only display a deprecation warning (if they are enabled). see issue in [Distributions.jl](https://github.com/JuliaStats/Distributions.jl/issues/1463)
... but as of 18 Mar 2022, throws an error...

`julia> pdf(b1, x)`
ERROR: MethodError: pdf(::Beta{Float64}, ::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}) is ambiguous. Candidates:
  pdf(d::Distribution{ArrayLikeVariate{N}}, x::AbstractArray{<:Real, M}) where {N, M} in Distributions at E:\Julia\.julia\packages\Distributions\vcKQj\src\common.jl:251
  pdf(d::UnivariateDistribution, X::AbstractArray) in Distributions at deprecated.jl:70
Possible fix, define
  pdf(::UnivariateDistribution, ::AbstractArray{T, M} where T<:Real) where M

Fix: insert period to enable broadcasting
`julia> pdf.(b1, x)`

**Comment by goedman** [comment]
Thanks @fpmenninger  I had noticed it and have updated several notebooks in SR2TuringPluto.jl v5 (not yet pushed as it is a considerable change from v4).

**Comment by goedman** [comment]
I think this has been fixed in Rel 4.0.5
