### ISSUE TITLE
`logpdf` to broadcasted `.logpdf`

### ISSUE THREAD

**Issue by filchristou** [StatisticalRethinkingJulia/StatisticalRethinkingTuring.jl#14]
Apparently some things changed and Chapter_04_part_1.jl Code 4.16  doesn't work.
Substituting `logpdf` to broadcasted `.logpdf` does the trick.

**Comment by goedman** [comment]
Yes, I think that happened because of a recent update to Distributions.jl.

**Comment by goedman** [comment]
Aah, I had updated those but not pushed. Rel v4.0.5 have been checked and updated.

Note: Chapter 1-5 have been checked, still working (slowly) on subsequent chapters.
