### ISSUE TITLE
Could not import Turing.ModeResult into StatisticalRethinking

### ISSUE THREAD

**Issue by FredericBlum** [StatisticalRethinkingJulia/StatisticalRethinkingTuring.jl#18]
Despite instantiating julia using the Project.toml, I got the following error:

```
Error requiring `Turing` from `StatisticalRethinking`

exception

LoadError: UndefVarError: `ModeResult` not defined

in expression starting at /Users/blum/.julia/packages/StatisticalRethinking/RYYWV/src/require/turing/turing_optim_sample.jl:5

in expression starting at /Users/blum/.julia/packages/StatisticalRethinking/RYYWV/src/require/turing/turing.jl:7

    top-level scope@turing_optim_sample.jl:5
    include(::Module, ::String)@Base.jl:457
    include(::String)@StatisticalRethinking.jl:1
    top-level scope@turing.jl:7
    include(::Module, ::String)@Base.jl:457
    include(::String)@StatisticalRethinking.jl:1
    top-level scope@Requires.jl:40
    eval@boot.jl:370[inlined]
    eval@StatisticalRethinking.jl:1[inlined]
    (::StatisticalRethinking.var"#3#12")()@require.jl:101
    macro expansion@timing.jl:393[inlined]
    err(::Any, ::Module, ::String, ::String, ::Any)@require.jl:47
    (::StatisticalRethinking.var"#2#11")()@require.jl:100
    withpath(::Any, ::String)@require.jl:37
    (::StatisticalRethinking.var"#1#10")()@require.jl:99
    listenpkg(::Any, ::Base.PkgId)@require.jl:20
    macro expansion@require.jl:98[inlined]
    __init__()@StatisticalRethinking.jl:31
    register_restored_modules(::Core.SimpleVector, ::Base.PkgId, ::String)@loading.jl:1115
    _include_from_serialized(::Base.PkgId, ::String, ::String, ::Vector{Any})@loading.jl:1061
    _require_search_from_serialized(::Base.PkgId, ::String, ::UInt128)@loading.jl:1506
    _require(::Base.PkgId, ::String)@loading.jl:1783
    _require_prelocked(::Base.PkgId, ::String)@loading.jl:1660
    macro expansion@loading.jl:1648[inlined]
    macro expansion@lock.jl:267[inlined]
    require(::Module, ::Symbol)@loading.jl:1611
    top-level scope@[Other: 13](http://localhost:1235/edit?id=253bb52c-a005-11ee-0a0f-6d20735f295d#)

❔

WARNING: could not import Turing.ModeResult into StatisticalRethinking
```

I guess this is a versioning problem? I will try other versions of Turing as soon as I get to it, I am just setting this repository up.

**Comment by goedman** [comment]
I have no idea what happened to this option. It might have been moved to related packages? Your best bet would be to check with the Turing folks. I tried to update to Turing v0.30 but couldn't (many package incompatibilities).

This is very unfortunate. But not really surprising as I haven't used Turing.jl for quite while and no longer have the knowledge nor the bandwidth to maintain the Turing projects in StatisticalRethinkingJulia and RegressionAndOtherStoriesJulia. 

I will need to make a decision what to do with the unsupported Turing projects in both StatisticalRethinkingJulia and RegressionAndOtherStoriesJulia. Most likely I will have to archive the projects in early 2024.

**Comment by FredericBlum** [comment]
Ok thanks. So your recommendation would be to go for the SR2Stan instead of Turing? Is this more of a capacity-orientated decision or are there performance/implementability advantages for Stan over Turing?

**Comment by goedman** [comment]
Not really, this is only based on the fact that I don't have the bandwidth to support the Turing projects. Both Stan and Turing have solid teams behind the implementations. I'd hoped over the last couple of years someone else would step up to work on the Turing projects, but realize that is a major time commitment (having done it now for quite some years :-).

**Comment by goedman** [comment]
By the way, I don't think Turing has dropped support for MAP and MLE, it might just have moved.

**Comment by FredericBlum** [comment]
Sadly I do not much about package development (yet) in Julia, otherwise I'd try to fix this myself. Can you point me to where in the StatisticalRethinking this likely goes wrong, and then I can check if I can fix this?

**Comment by goedman** [comment]
In `./src/turing/turing_optim_sample.jl` I import `import .Turing: ModeResult`. I think that object is no longer defined in Turing. I've been looking a bit in the docs if estimating MAP and/or MLE values is still supported, but couldn't find it anymore.
Will take another look.

**Comment by goedman** [comment]
@FredericBlum 

Ok, found out what is happening. ModeResult is now defined in an  extension (TuringOptimExt). Progress!

**Comment by goedman** [comment]
Just pushed a new version of StatisticalRethinking (v4.8.0). Did an initial test with the TuringGuide.jl and found the MAP stuff working now. The cells with MCMCThread() fail. But by removing the MCMCThread() part and the last part all cells work.
Let me try some other notebooks in SR2TuringPluto.jl.

**Comment by goedman** [comment]
@FredericBlum Also pushed SR2TuringPluto.jl v5.8.0 ti Github. By inserting `using Optim` early on in the `begin..end` block with `all using ...` statements I think all notebooks will work again.

Update: Most notebooks do work but often the `begin..end` block with the using statements needs to be run a second time. Need to check how the TuringOptimExt is defined.

**Comment by goedman** [comment]
In v5.2.0 I inserted the using Optim statements.

**Comment by FredericBlum** [comment]
Thanks! I will have a look at it as soon as I can
