### ISSUE TITLE
@formula not defined in Clip-00-04-05t.jl

### ISSUE THREAD

**Issue by sbacelar** [StatisticalRethinkingJulia/StatisticalRethinkingTuring.jl#6]
When running `Clip-00-04-05t.jl` in Pluto or in REPL I get this error:

```
julia> m = lm(@formula(height ~ weight), df)
ERROR: LoadError: UndefVarError: @formula not defined
in expression starting at REPL[7]:1
```

**Comment by goedman** [comment]
Oops, I some time ago limited what's imported from GLM (as I started to get conflicts if I remember well).

A quick workaround is probably expanding the `@quickactivate "StatisticalRethinkingTuring"` begin-end block to:
```
begin
	@quickactivate "StatisticalRethinkingTuring"
	using GLM
	using StatisticalRethinking
end
```

**Comment by sbacelar** [comment]
Thank you. Now it works. 
Note: I have deleted all the commands `@quickactivate` because I had problems with the new version of `Pluto.jl`

**Comment by goedman** [comment]
Which version of Pluto are you using? Just tried it on my system and noticed Clip-00-04-05.jl was missing `Pkg` in the first line `using Pkg, DrWatson`, but then it worked fine with `@quickactivate ...`.

**Comment by sbacelar** [comment]
I am using v.0.15.1. 
Please see https://github.com/fonsp/Pluto.jl/wiki/%F0%9F%8E%81-Package-management

**Comment by goedman** [comment]
I'm also using v0.15.1. I thought @quickactivate disables Pluto's package management. So how do your first couple of cells look?

**Comment by sbacelar** [comment]
Simply:
`using DrWatson`
`using StatisticalRethinking`

**Comment by goedman** [comment]
Thank you. I'll think about that option.
