### ISSUE TITLE
Models with multivariate normal priors?

### ISSUE THREAD

**Issue by itsdfish** [StatisticalRethinkingJulia/StatisticalRethinkingTuring.jl#9]
Hello Rob,

I have been looking for Turing models that use multivariate normal priors. Here is an example in [Stan](https://mc-stan.org/docs/2_18/stan-users-guide/multivariate-hierarchical-priors-section.html), but I am not sure exactly how to translate it to Turing. 

I noticed that Chapter 14 in Statistical Rethinking has examples, but those have not been implemented in this repository. What is the status for these models?

**Comment by goedman** [comment]
Hi Chris, I'll have a look. I thought there were 2 examples in TuringModels, but it's been a while since I looked at these.

**Comment by itsdfish** [comment]
Thanks, Rob. I did not realize there was a different repo. I found this model with varying [slopes](https://statisticalrethinkingjulia.github.io/TuringModels.jl/models/varying-slopes-cafe/).  At the bottom of this [Stan](https://mc-stan.org/docs/2_18/stan-users-guide/multivariate-hierarchical-priors-section.html) example, is description of an optimization using Cholesky  decomposition, which is supposed to reduce numerical errors and improve efficiency. It looks like that might be beneficial because the Turing example does not work with delta = .65. Are you familiar with how to do the optimization in Turing?

**Comment by goedman** [comment]
Unfortunately I'm not familiar with the optimizations possible in Turing. I noticed Rik (@rikhuijzer) covers 5 or 6 varying slope models in TuringModels.jl which are probably closest to what you are looking for. Not sure to what extent these models were derived and updated from the two earlier models Richard Torkar developed for chapter 14. As you know, six years ago, when Richard worked on this, these kind of models were still difficult in Turing. I know Rik made a bunch of improvements and he might be in a better position to answer your question.

In fact with Stan 2.28_RC1 I also need to re-consider several new options for StanSample. I've experimented a bit with the Stan ( C++) based threads but have not really explored map_rect, reduce_sum, OpenCL, Intel's TBB blocks and a new ODE solver (which all will be available in the cmdstan v2.28.0 binary) yet. Neither have I really looked into section 1.13 of the Stan User's Guide (Cholesky optimization).

In a sense these are beyond the introductory level covered in StanJulia and StatisticalRethinking. I do want to keep the option open to include optimizations as long as it doesn't complicate "introductory" usage.

**Comment by rikhuijzer** [comment]
> I have been looking for Turing models that use multivariate normal priors. Here is an example in Stan, but I am not sure exactly how to translate it to Turing.

What are you trying to translate exactly and what exactly is not working? Maybe, the QR decomposition example at <https://storopoli.io/Bayesian-Julia/pages/11_Turing_tricks/> helps.

**Comment by itsdfish** [comment]
Hi @rikhuijzer, I am trying to use a Cholesky factorization optimization described [here](https://mc-stan.org/docs/2_18/stan-users-guide/multivariate-hierarchical-priors-section.html). This is used for various types of models with multivariate normal priors. Having a few examples might be useful to the Turing community. 

The model that I am working on currently uses a [diag_premultiply](https://github.com/stan-dev/example-models/blob/master/Bayesian_Cognitive_Modeling/CaseStudies/MPT/MPT_5_Stan.R#L39l) with a LKJ prior, but I don't understand what it is doing or how to implement it in Turing.  Any help would be appreciated. If the Cholesky factorization used in Stan proves to be useful and straightforward, I would be willing to submit a PR. 

Update: Sorry. I had to fix the second link.

**Comment by rikhuijzer** [comment]
Nope sorry I don't know. Maybe you can ask this question at Discourse or the Turing slack channel in https://julialang.slack.com.

**Comment by itsdfish** [comment]
Thanks. I asked a question on Slack. I tried implementing the model based on your varying slopes example, but I received a few errors. If I find out how to implement the optimization, I will report back. Thank you.

**Comment by rikhuijzer** [comment]
> your varying slopes example

That's too much credit to me. Many people have contributed to that file (even though Git lost track of the contributors for that file).

**Comment by itsdfish** [comment]
Well, thanks to you and the other contributors. 

By the way, there is an [effort](https://github.com/JuliaStats/Distributions.jl/pull/1339) to add the optimization to the LKJ prior distribution, which will greatly speed up the code and improve numerical stability of multilevel models. I will open a new issue so I can add the improvements when they are available.
